[package]
name = "cursetool-rs"
version = "0.1.0"
authors = ["Maxwell L-T <maxwell.lt@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
reqwest = "0.10.10"
log = "0.4.11"
simplelog = "0.9.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
